Repository VerzatileDevOrg/C_image_processing, pull requests merged in 2023-08, with the labels that each got.

#1 Refactoring and Structural Improvements
  C_image_processing/.gitignore
  C_image_processing/assets/images/test_image.bmp
  C_image_processing/filters/black_and_white_filter.c
  C_image_processing/filters/bright_filter.c
  C_image_processing/filters/dark_filter.c
  C_image_processing/filters/negative_filter.c
  C_image_processing/filters/rgb_to_gray_filter.c
  C_image_processing/filters/sepia_filter.c
  C_image_processing/main.c
  filters/black_and_white_filter.c
  filters/bright_filter.c
  filters/negative_filter.c
  filters/rgb_to_gray_filter.c
  filters/sepia_filter.c
  main.c
Labels: enhancement

#2 Refactored Codebase 2
  C_image_processing/.gitignore
  C_image_processing/.vscode/c_cpp_properties.json
  C_image_processing/.vscode/tasks.json
  C_image_processing/filters/black_and_white_filter.c
  C_image_processing/filters/bright_filter.c
  C_image_processing/filters/dark_filter.c
  C_image_processing/filters/negative_filter.c
  C_image_processing/filters/rgb_to_gray_filter.c
  C_image_processing/filters/sepia_filter.c
  C_image_processing/main.c
Labels: enhancement, Refactoring

#3 .vscode Ignored Add your own!
  C_image_processing/.vscode/c_cpp_properties.json
  C_image_processing/.vscode/tasks.json
Labels: invalid

#5 Fixed (1) / add (2) filters, modified UI
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  C_image_processing/filters/dark_filter.c
  C_image_processing/filters/sepia_filter.c
  README.md
  src/.gitignore
  src/assets/fonts/big_noodle_titling.ttf
  src/assets/fonts/big_noodle_titling_oblique.ttf
  src/assets/images/test_image.bmp
  src/filters/black_and_white_filter.c
  src/filters/bright_filter.c
  src/filters/dark_filter.c
  src/filters/emboss_filter.c
  src/filters/negative_filter.c
  src/filters/pixelate_filter.c
  src/filters/rgb_to_gray_filter.c
  src/filters/sepia_filter.c
  src/main.c
Labels: bug, enhancement

#8 refactored filters (All), GTK GUI
  .gitignore
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  README.md
  readme_image_0.png
  readme_image_1.png
  readme_image_2.png
  readme_image_3.png
  readme_images/readme_image_0.png
  readme_images/readme_image_1.png
  readme_images/readme_image_2.png
  readme_images/readme_image_3.png
  readme_images/readme_image_4.png
  readme_images/readme_image_5.png
  readme_images/readme_image_6.png
  readme_images/readme_image_7.png
  src/filters/black_and_white_filter.c
  src/filters/bright_filter.c
  src/filters/dark_filter.c
  src/filters/emboss_filter.c
  src/filters/negative_filter.c
  src/filters/pixelate_filter.c
  src/filters/rgb_to_gray_filter.c
  src/filters/sepia_filter.c
  src/gtk_gui.c
  src/main.c
  tests/filters_test.c
Labels: bug, documentation, Refactoring

#11 [ADD] / [FIX] > Image Converters / Black White filter
  src/assets/images/test_ima.bmp
  src/assets/images/testpng.png
  src/converters/bmp_to_jpeg.c
  src/converters/bmp_to_png.c
  src/converters/jpeg_to_bmp.c
  src/converters/png_to_bmp.c
  src/gtk_gui.c
  src/main.c
Labels: enhancement
